name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: "11"
    - name: Run unit tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 26
          arch: x86_64
          target: default
          script: ./gradlew check && ./gradlew connectedCheck
